// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";
import GlobalContextsProvider from "../components/plasmic/inprodi_design_system/PlasmicGlobalContextsProvider";
import { PlasmicComponents } from "../components/plasmic/inprodi_design_system/PlasmicComponents";
import { useRouter } from "next/router";

function Components() {
  return (
    <GlobalContextsProvider>
      <PageParamsProvider__
        route={useRouter()?.pathname}
        params={useRouter()?.query}
        query={useRouter()?.query}
      >
        <PlasmicComponents />
      </PageParamsProvider__>
    </GlobalContextsProvider>
  );
}

export default Components;
