// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";
import GlobalContextsProvider from "../components/plasmic/inprodi_design_system/PlasmicGlobalContextsProvider";
import { PlasmicTypographies } from "../components/plasmic/inprodi_design_system/PlasmicTypographies";
import { useRouter } from "next/router";

import {ColorSchemeContext} from "@/components/plasmic/inprodi_design_system/PlasmicGlobalVariant__ColorScheme";

function Typographies() {
  return (
    <GlobalContextsProvider>
      <PageParamsProvider__
        route={useRouter()?.pathname}
        params={useRouter()?.query}
        query={useRouter()?.query}
      >
        <PlasmicTypographies />
      </PageParamsProvider__>
    </GlobalContextsProvider>
  );
}

export default Typographies;
